<a href="https://colab.research.google.com/github/mkh-ai/mkh-ai/blob/main/array_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1 = [1,2,3,4]
arr1 = np.array(data1)


In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
data2 = (5,6,7,8)
arr2= np.array(data2)


In [8]:
arr2.ndim    # arr2 ning olchami


1

**Ikki va undan yuqori bolgan massivlar**

In [11]:
data3 = [[1,2,3,4,5],[6,7,8,9]]
arr3 = np.array(data3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [5]:
data4 = [[1,2,3,4],[5,6,7,8,],[9,10,11,12]]   # 3 olchamli massiv
arr4 = np.array(data4)


In [8]:
arr4.ndim



2

# shape va sisze metodlari

In [9]:

arr4.shape  # masssivning qator va ustunlarini sonini korsatadi


(3, 4)

In [20]:
arr4.size   # massiv olchamini chiqaradi

12

# N olchamli massiv yaratishning boshqa usullarni


**zeros va ones funksiyalari** 

In [22]:
arr5 = np.zeros((3,4))  # barcha elementlari 0 ga teng massiv yaratadi
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arr6 = np.ones((5,8))   # barcha elementlari 1 ga teng massiv yaratadi
arr6

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**arange funksiyasi yordanida yaratish**

In [25]:
arr7 = np.arange(34,500,30)  # 30 qadam bilan massiv yaratdi
arr7

array([ 34,  64,  94, 124, 154, 184, 214, 244, 274, 304, 334, 364, 394,
       424, 454, 484])

# Random funksiyasi yordamida yaratish

In [10]:
arr8 = np.random.randn(4,5)  # (4,5) olchamli elementlari 0 va 1 oraligidagi tahminiy qiymatlardan tasshkil topgana
arr8

array([[ 0.86729019,  0.33059438,  1.16007321, -0.69078763,  0.23957368],
       [ 2.05102979, -0.04529707,  0.18126415,  0.43854745,  1.62920157],
       [-1.11347006, -0.72349974, -0.82726793, -0.33558207, -1.40298248],
       [-1.08099356, -1.47520863,  0.51933904, -0.44859242, -0.45046735]])

In [11]:
arr9 = np.random.randint(28,size=(3,6))  # maximal qiymati 28 ga teng bolgan (3,6) olchamli tahminiy qiymatlardan tashkil topgan massiv
arr9

array([[19,  1, 21,  2, 10,  5],
       [25, 11, 27,  8, 11,  8],
       [12, 11, 17,  8,  9, 11]])

In [12]:
arr10 = np.random.rand(5,6)
arr10

array([[0.46917503, 0.75628404, 0.13459108, 0.35858196, 0.04975898,
        0.96091065],
       [0.20737618, 0.77195476, 0.25467282, 0.23324701, 0.64659113,
        0.80680136],
       [0.33847713, 0.0884518 , 0.79000095, 0.13213114, 0.98787153,
        0.24837722],
       [0.02795409, 0.19759791, 0.22969841, 0.48521847, 0.85293056,
        0.97993388],
       [0.67293241, 0.40005928, 0.93587299, 0.09387016, 0.76118287,
        0.38367871]])