<a href="https://colab.research.google.com/github/mkh-ai/mkh-ai/blob/main/creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Bismillah


In [2]:
import numpy as np

In [4]:
data1 = [2,4,5,3.4,9] #list
arr1 = np.array(data1)  # array
arr1

array([2. , 4. , 5. , 3.4, 9. ])

In [7]:
data2 = (2,4,3,2,1.3)
arr2 = np.array(data2)
arr2

array([2. , 4. , 3. , 2. , 1.3])

# Massiv o'lchami


In [8]:
arr1.ndim


1

# Nested list


In [11]:
data3 = [[1,2,3,4], [5,6,7,8]]
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Shape va Size metodi

In [12]:
arr3.shape # qator va usrunlarini sonini korsatadi


(2, 4)

In [14]:
arr3.size # arrayning elementlar soni

8

# Array yaratishning zero va ones sussullari

In [16]:
arr4 = np.zeros((3,6))# barcha elementlari o ga teng array yaratadi
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr5 = np.ones((5,8)) # barcha elementlari 1 ga teng array yaratadi
arr5

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# Arange funksiyasi 

In [19]:
arr6 = np.arange(3,98,3) # malum  oraliqdagi array yaratish
arr6

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])